import type { PointWriteInput } from './point.types'

export const seedPoints: PointWriteInput[] = [
  {
    id: '1',
    name: 'Playa Chicama',
    lat: -7.7032,
    lng: -79.4346,
    categories: ['otros'],
    rating: 4.8,
    description: 'La famosa playa de Chicama, ideal para surf y caminatas frente al mar.',
    contact: '',
    keywords: ['playa', 'surf', 'olas', 'atardecer', 'malecón'],
  },
  {
    id: '2',
    name: 'Chicamalandia',
    lat: -7.7011499,
    lng: -79.4395159,
    categories: ['tienda', 'venta_tablas', 'alquiler_tablas'],
    rating: 4.7,
    description: 'Tienda de surf y deportes acuáticos en la zona de Chicama.',
    contact: '',
    keywords: ['tabla', 'surf', 'alquiler', 'neopreno', 'wax', 'accesorios'],
  },
  {
    id: '3',
    name: 'Surf Shop la Ola más larga del Mundo',
    lat: -7.703739,
    lng: -79.4419974,
    categories: ['tienda', 'venta_tablas'],
    rating: 4.6,
    description: 'Surf shop local para equipos, accesorios y artículos de playa.',
    contact: '',
    keywords: ['tabla', 'surf shop', 'accesorios', 'trajes', 'bloqueador'],
  },
  {
    id: '4',
    name: 'Chicama Surfing',
    lat: -7.6998102,
    lng: -79.4370171,
    categories: ['tienda', 'alquiler_tablas'],
    rating: 4.5,
    description: 'Punto local vinculado al surf con alquiler y apoyo a viajeros.',
    contact: '',
    keywords: ['surf', 'alquiler', 'tablas', 'viajeros', 'clases'],
  },
  {
    id: '5',
    name: 'Caluchef',
    lat: -7.70255,
    lng: -79.4410151,
    categories: ['restaurante'],
    rating: 4.5,
    description: 'Restaurante local en Puerto Malabrigo.',
    contact: '',
    keywords: ['almuerzo', 'cena', 'comida', 'restaurante'],
  },
  {
    id: '6',
    name: 'Charki Restobar',
    lat: -7.701442,
    lng: -79.4396528,
    categories: ['restaurante'],
    rating: 4.5,
    description: 'Restobar en la zona céntrica de Chicama.',
    contact: '',
    keywords: ['restobar', 'bebidas', 'comida', 'cena'],
  },
  {
    id: '7',
    name: 'Burgers And Brownies Chicama',
    lat: -7.7030798,
    lng: -79.4424204,
    categories: ['restaurante'],
    rating: 4.4,
    description: 'Lugar de hamburguesas, brownies y comida rápida.',
    contact: '',
    keywords: ['hamburguesas', 'brownies', 'snacks', 'postres', 'fast food'],
  },
  {
    id: '8',
    name: 'El Point',
    lat: -7.7009953,
    lng: -79.4396357,
    categories: ['restaurante'],
    rating: 4.4,
    description: 'Restaurante y punto de encuentro cerca de la playa.',
    contact: '',
    keywords: ['desayuno', 'almuerzo', 'cena', 'restaurante'],
  },
  {
    id: '9',
    name: 'El Mirador',
    lat: -7.7009872,
    lng: -79.439112,
    categories: ['restaurante'],
    rating: 4.4,
    description: 'Restaurante local con vista y ambiente relajado.',
    contact: '',
    keywords: ['mirador', 'comida', 'vista', 'café'],
  },
  {
    id: '10',
    name: 'Blue Beach House',
    lat: -7.7021739,
    lng: -79.4362104,
    categories: ['hospedaje'],
    rating: 4.6,
    description: 'Hospedaje cerca de la playa para surfistas y visitantes.',
    contact: '',
    keywords: ['hotel', 'habitaciones', 'hospedaje', 'surf trip'],
  },
  {
    id: '11',
    name: 'Casa Sol de Chicama',
    lat: -7.7018468,
    lng: -79.4401062,
    categories: ['hospedaje'],
    rating: 4.6,
    description: 'Hospedaje en Chicama para estadías cortas y largas.',
    contact: '',
    keywords: ['casa', 'habitaciones', 'hotel', 'estadía'],
  },
  {
    id: '12',
    name: 'Chicama Boutique Hotel',
    lat: -7.7046416,
    lng: -79.4439652,
    categories: ['hospedaje'],
    rating: 4.7,
    description: 'Hotel boutique en la zona turística de Puerto Malabrigo.',
    contact: '',
    keywords: ['hotel', 'boutique', 'habitaciones', 'reserva'],
  },
  {
    id: '13',
    name: 'Chicama Hostal',
    lat: -7.703051,
    lng: -79.4415351,
    categories: ['hospedaje'],
    rating: 4.4,
    description: 'Hostal céntrico cerca del área de surf.',
    contact: '',
    keywords: ['hostal', 'habitación', 'descanso', 'viajeros'],
  },
  {
    id: '14',
    name: 'Hotel Omnidays',
    lat: -7.7016013,
    lng: -79.439784,
    categories: ['hospedaje'],
    rating: 4.4,
    description: 'Hospedaje en el centro de Puerto Malabrigo.',
    contact: '',
    keywords: ['hotel', 'habitaciones', 'baño', 'descanso'],
  },
  {
    id: '15',
    name: 'Hostal Los Delfines Chicama',
    lat: -7.7040013,
    lng: -79.4433393,
    categories: ['hospedaje'],
    rating: 4.5,
    description: 'Hostal para visitantes de playa y surf.',
    contact: '',
    keywords: ['hostal', 'dormir', 'habitaciones', 'turismo'],
  },
  {
    id: '16',
    name: 'Interbank',
    lat: -7.7021199,
    lng: -79.4379938,
    categories: ['otros'],
    rating: 4.2,
    description: 'Punto bancario útil para retiros y operaciones básicas.',
    contact: '',
    keywords: ['banco', 'cajero', 'atm', 'retiro', 'dinero'],
  },
  {
    id: '17',
    name: 'Posta Médica Malabrigo',
    lat: -7.7013536,
    lng: -79.4365063,
    categories: ['otros'],
    rating: 4.3,
    description: 'Centro de salud para atención básica en Puerto Malabrigo.',
    contact: '',
    keywords: ['clínica', 'salud', 'medicina', 'emergencia', 'doctor'],
  },
  {
    id: '18',
    name: 'Municipalidad de Rázuri',
    lat: -7.70226,
    lng: -79.4377591,
    categories: ['otros'],
    rating: 4.0,
    description: 'Sede municipal y punto de trámites locales.',
    contact: '',
    keywords: ['municipalidad', 'trámites', 'información', 'servicios'],
  },
  {
    id: '19',
    name: 'El Hombre Point Break',
    lat: -7.7025747,
    lng: -79.4429946,
    categories: ['otros'],
    rating: 4.6,
    description: 'Punto turístico conocido por sus vistas y cultura surf.',
    contact: '',
    keywords: ['point break', 'mirador', 'fotos', 'olas', 'turismo'],
  },
]
