"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _places_directory_list from './places-directory-list.bones.json'
import _featured_point_card from './featured-point-card.bones.json'
import _map_dock_panel from './map-dock-panel.bones.json'

registerBones({
  "places-directory-list": _places_directory_list,
  "featured-point-card": _featured_point_card,
  "map-dock-panel": _map_dock_panel,
})
